## 2.1.1 创建ndarray数组

In [3]:
import numpy as np

In [4]:
data1 = [5,7,9,20]   #列表
arr1 = np.array(data1)
arr1

array([ 5,  7,  9, 20])

In [5]:
data2 = (5,7,9,20)   #元组
arr2 = np.array(data2)
arr2

array([ 5,  7,  9, 20])

In [6]:
data3 = [[1,2,3,4],[5,6,7,8]]  #多维数组
arr3 = np.array(data3)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### ndarray是一个通用的同构数据容器，即其中的所有元素都需要是相同的类型。当创建好一个ndarray数组时，同时会在内存中存储ndarray的shape和dtype。shape是ndarray维度大小的元组，dtype是解释说明ndarray数据类型的对象.

In [7]:
arr3.shape

(2, 4)

In [8]:
arr3.dtype

dtype('int32')

### 当序列中有整数和浮点数时，NumPy会把数组的dtype定义为浮点数据类型

In [9]:
data4 = [1.3,2,3.45,5]
arr4 = np.array(data4)
arr4

array([1.3 , 2.  , 3.45, 5.  ])

In [12]:
arr4.dtype

dtype('float64')

### zeros函数可以创建指定长度或形状的全0数组

In [13]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### ones函数可以创建指定长度或形状的全1数组

In [16]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### empty函数可以创建一个没有具体值的数组（即垃圾值）

In [22]:
np.empty((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

### arange函数类似于Python的内置函数range

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### ones_like函数可以根据传入的数组形状和dtype创建全1数组

In [24]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
arr5 = np.ones_like(arr3)
arr5

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
arr5.dtype

dtype('int32')

## 2.1.2 ndarray对象属性

In [28]:
data = [[2,4,5],[3,5,7]]
arr = np.array(data)
arr

array([[2, 4, 5],
       [3, 5, 7]])

In [29]:
arr.ndim   #数据轴的个数

2

In [30]:
arr.size   #元组的总个数

6

In [31]:
arr.itemsize         #数据中每个元组的字节大小

4

In [32]:
arr.dtype            #数据类型

dtype('int32')

In [33]:
arr.shape         #数组的维度

(2, 3)

### arr数组的数据类型是int32位的，对于计算机而言，1个字节是8位，所以arr的itemsize属性值为4。

## 2.1.3 ndarray数据类型

### 在创建数组时，NumPy会为新建的数组推断出一个合适的数据类型。同样，也可以通过dtype给创建的数组指定数据类型

In [35]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [36]:
arr1.dtype

dtype('int32')

In [37]:
arr2 = np.arange(5,dtype='float64')
arr2

array([0., 1., 2., 3., 4.])

In [38]:
arr2.dtype

dtype('float64')

### 浮点数（float）、整数（int）、复数（complex）、布尔值（bool）、字符串（string_）和Python对象（object）

### 对于创建好的ndarray，可通过astype方法进行数据类型的转换

In [39]:
arr1 = np.arange(6)
arr1

array([0, 1, 2, 3, 4, 5])

In [40]:
arr1.dtype

dtype('int32')

In [41]:
arr2 = arr1.astype(np.float64)
arr2

array([0., 1., 2., 3., 4., 5.])

In [43]:
arr2 = arr1.astype('float64')
arr2

array([0., 1., 2., 3., 4., 5.])

In [44]:
arr2.dtype

dtype('float64')

In [46]:
arr3 = arr1.astype('string_')
arr3

array([b'0', b'1', b'2', b'3', b'4', b'5'], dtype='|S11')

In [47]:
arr3.dtype

dtype('S11')

### 如果将浮点数转换为整数，并不会使用四舍五入的方式来转换，而是元素的小数部分都会被截断

In [48]:
arr = np.array([2.3,3.5,4,7,5.6])
arr

array([2.3, 3.5, 4. , 7. , 5.6])

In [49]:
arr.astype('int32')

array([2, 3, 4, 7, 5])

### 如果数组是字符串类型且全是数字的话，也可以通过astype方法将其转换为数值类型

In [50]:
arr3

array([b'0', b'1', b'2', b'3', b'4', b'5'], dtype='|S11')

In [51]:
arr3.astype(np.int32)

array([0, 1, 2, 3, 4, 5])

### 如果字符串中有字符时，转换时就会报错

In [52]:
arr = np.array([2,'hello'])
arr

array(['2', 'hello'], dtype='<U11')

In [53]:
arr.astype(np.int32)

ValueError: invalid literal for int() with base 10: 'hello'

### astype方法也可以通过另外一个数组的dtype进行转换。astype方法会创建一个新的数组，并不会改变原有数组的数据类型

In [54]:
arr1 = np.arange(10)
arr1.dtype

dtype('int32')

In [55]:
arr2 = np.ones(5)
arr2.dtype

dtype('float64')

In [56]:
arr3 = arr1.astype(arr2.dtype)
arr3.dtype

dtype('float64')

### 原数组变化情况

In [57]:
arr = np.arange(3)
arr.dtype

dtype('int32')

In [58]:
arr.astype('float64')

array([0., 1., 2.])

In [59]:
arr

array([0, 1, 2])

## 2.1.4 数组变换

### 对于定义好的数组，可以通过reshape方法改变其数据维度。传入的参数为新维度的元组.

In [60]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
arr.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 多维数组也可以被重塑

In [63]:
arr = np.array([[3,4,5],[6,7,8]])
arr.reshape((3,2))

array([[3, 4],
       [5, 6],
       [7, 8]])

### reshape的参数中的一维参数可以设置为-1，表示数组的维度可以通过数据本身来推断。

In [64]:
arr = np.arange(12)
arr.reshape((3,-1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 与reshape相反的方法是数据散开（ravel）数据或扁平化（flatten）

In [65]:
arr = np.arange(10).reshape((5,2))
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [68]:
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [70]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 数据重塑不会改变原数组。

### 数组合并用于几个数组间的操作，concatenate方法通过指定轴方向，将多个数组合并在一起

In [71]:
arr1 = np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
arr2 = np.arange(12,24).reshape(3,4)
arr2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [73]:
np.concatenate([arr1,arr2],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [74]:
np.concatenate([arr1,arr2],axis=1)

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

### NumPy中提供了几个比较简单易懂的方法，也可以进行数组合并，如vstack和hstack。

In [75]:
np.vstack((arr1,arr2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [76]:
np.hstack((arr1,arr2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

### 数组拆分是数组合并的相反操作，通过split方法可以将数组拆分为多个数组

In [77]:
arr = np.arange(12).reshape((6,2))
arr 

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [78]:
np.split(arr,[2,4])

[array([[0, 1],
        [2, 3]]), array([[4, 5],
        [6, 7]]), array([[8, 9]])]

### 数组转置和轴对换

### 转置是数组重塑的一种特殊形式，可以通过transpose方法进行转置。transpose方法需要传入轴编号组成的元组，这样就完成了数组的转置。

In [80]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
arr.transpose((1,0))

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### 除了使用transpose方法外，数组有着T属性，可用于数组的转置。

In [84]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### ndarray的swapaxes方法用于轴对换。

In [85]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [92]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## 2.1.5 NumPy的随机数函数

### 在numpy.random模块中，提供了多种随机数生成函数。例如，可以通过randint函数生成整数随机数

In [94]:
import random

In [97]:
arr = np.random.randint(100,200,size=(5,4))
arr

array([[183, 186, 192, 196],
       [178, 177, 167, 177],
       [104, 174, 151, 103],
       [101, 193, 172, 101],
       [116, 160, 126, 155]])

### random模块中还提供了一些概率分布的样本值函数，如randn函数，例如，生成平均数为0，标准差为1的正态分布的随机数。

In [99]:
arr = np.random.randn(2,3,4)
arr

array([[[-1.59683416, -0.4044982 , -0.27074834,  0.42700882],
        [ 0.46378883, -0.76672545, -0.959657  , -1.2542587 ],
        [-0.23882418,  0.20906365, -3.15124604, -0.82585876]],

       [[ 0.50683729,  0.36232043, -0.56848971,  0.5220639 ],
        [-0.19307251,  0.76630572,  1.34074261,  1.80531844],
        [-0.24559815, -1.77596771,  0.6354953 ,  2.69003357]]])

### 通过normal函数生成指定均值和标准差的正态分布的数组。

In [101]:
arr = np.random.normal(4,5,size=(3,5))
arr

array([[ 8.83148492,  3.92807385,  8.8951369 ,  4.4168898 ,  1.91820396],
       [ 0.65488933,  3.4695343 ,  8.79209356,  3.64788022, -0.66830035],
       [ 9.26756754, 13.8135426 ,  8.74241196,  8.31379511,  5.11927104]])

### 最后来看看permutation和shuffle函数的用法

In [102]:
arr = np.random.randint(100,200,size=(5,4))
arr

array([[139, 150, 182, 169],
       [118, 124, 176, 181],
       [198, 140, 181, 171],
       [136, 192, 145, 189],
       [165, 129, 181, 112]])

In [104]:
np.random.permutation(arr)

array([[118, 124, 176, 181],
       [136, 192, 145, 189],
       [165, 129, 181, 112],
       [139, 150, 182, 169],
       [198, 140, 181, 171]])

In [105]:
arr

array([[139, 150, 182, 169],
       [118, 124, 176, 181],
       [198, 140, 181, 171],
       [136, 192, 145, 189],
       [165, 129, 181, 112]])

In [107]:
np.random.shuffle(arr)
arr

array([[139, 150, 182, 169],
       [118, 124, 176, 181],
       [136, 192, 145, 189],
       [165, 129, 181, 112],
       [198, 140, 181, 171]])