# 2.2 数组的索引和切片

In [1]:
import numpy as np

## 2.2.1 数组的索引

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[3]

3

In [4]:
arr[-1]

9

In [6]:
arr[2] = 123

In [7]:
arr

array([  0,   1, 123,   3,   4,   5,   6,   7,   8,   9])

### 从代码中可以看出，数组的切片返回的是原始数组的视图。简单地说，视图就是原始数组的表现形式，切片操作并不会产生新数据，这就意味着在视图上的操作都会使原数组发生改变。

In [8]:
arr

array([  0,   1, 123,   3,   4,   5,   6,   7,   8,   9])

In [9]:
arr[3]

3

In [10]:
arr[3] = 88

In [11]:
arr1 = arr[-3:-1]
arr1

array([7, 8])

In [12]:
arr1[:] = 77
arr

array([  0,   1, 123,  88,   4,   5,   6,  77,  77,   9])

### 如果需要的并非视图而是要复制数据，则可以通过copy方法来实现

In [13]:
arr

array([  0,   1, 123,  88,   4,   5,   6,  77,  77,   9])

In [26]:
arr1 = arr[1].copy()
arr1 = 34
arr

array([[[12, 12, 12],
        [12, 12, 12]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### 数组的切片和索引返回都是原始数组的视图。

### 对于二维数组，可在单个或多个轴向上完成切片，也可以跟整数索引一起混合使用

In [15]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
arr[0]

array([0, 1, 2, 3, 4])

In [17]:
arr[2]

array([10, 11, 12, 13, 14])

### 如果需要获取各个元素，可通过以下办法

In [18]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
arr[0][3]

3

In [20]:
arr[0,3]

3

### 在高维数组中，如果省略后面的索引，则会返回低一个维度的数组

In [33]:
arr = np.arange(12).reshape(2,2,3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [34]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5]])

### 标量值和数组都可以复制给arr[0]

In [35]:
old = arr[0].copy()
arr[0] = 12
arr

array([[[12, 12, 12],
        [12, 12, 12]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [36]:
arr[0] = old
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### 同样，类似于二维数组的切片，也可以索引到想要的部分元素或单个元素

In [37]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [38]:
arr[1,1]

array([ 9, 10, 11])

In [40]:
arr[0,1,2]

5

## 2.2.2 数组的切片

In [41]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [42]:
arr[2:5]

array([2, 3, 4])

### 多维数组的切片是按照轴方向进行的，当在中括号中输入一个参数时，数组就会按照0轴（也就是第一轴）方向进行切片

In [43]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
arr[2:]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

### 通过传入多个参数（可以是整数索引和切片），即可完成任意数据的获取

In [47]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [48]:
arr[:,1]

array([ 1,  4,  7, 10])

In [50]:
arr[:,1:2]

array([[ 1],
       [ 4],
       [ 7],
       [10]])

In [51]:
arr[2:,1:]

array([[ 7,  8],
       [10, 11]])

### 只有使用冒号才会选取整个轴

## 2.2.3 布尔型索引

In [95]:
fruits = np.array(['apple','banana','pear','banana','pear','apple','pear'])
datas = np.random.randint(-1,1,size=(7,5))

In [96]:
fruits

array(['apple', 'banana', 'pear', 'banana', 'pear', 'apple', 'pear'],
      dtype='<U6')

In [97]:
datas

array([[ 0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, -1],
       [-1,  0,  0,  0, -1],
       [-1,  0, -1,  0, -1],
       [ 0, -1,  0,  0,  0],
       [-1,  0,  0, -1,  0]])

### 如果每个水果对应于datas数组中的每一行，我们要取出‘pear’对应的datas的行，这时就需要用到布尔选择器

In [98]:
fruits == 'pear'

array([False, False,  True, False,  True, False,  True])

In [99]:
datas[fruits == 'pear']

array([[ 0,  0,  0,  0, -1],
       [-1,  0, -1,  0, -1],
       [-1,  0,  0, -1,  0]])

### 布尔型数组的长度必须和被索引的轴长度一致。

### 既然可以使用布尔选择，那么也同样适用于不等号（! =）、负号（-）、和（&）、或（|）

In [100]:
datas[fruits != 'pear']

array([[ 0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0],
       [-1,  0,  0,  0, -1],
       [ 0, -1,  0,  0,  0]])

In [101]:
datas[(fruits == 'apple')|(fruits == 'banana')]

array([[ 0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0],
       [-1,  0,  0,  0, -1],
       [ 0, -1,  0,  0,  0]])

### 此外，布尔数组也可以结合切片和索引来使用

In [102]:
datas[fruits =='pear',2:]

array([[ 0,  0, -1],
       [-1,  0, -1],
       [ 0, -1,  0]])

In [103]:
datas[fruits == 'pear',2]

array([ 0, -1,  0])

### 通过以下代码可以完成datas数组中的0值替换为1值

In [104]:
datas[datas == 0] = 1
datas


array([[ 1,  1,  1,  1, -1],
       [ 1,  1,  1,  1,  1],
       [ 1,  1,  1,  1, -1],
       [-1,  1,  1,  1, -1],
       [-1,  1, -1,  1, -1],
       [ 1, -1,  1,  1,  1],
       [-1,  1,  1, -1,  1]])

## 2.2.4 花式索引

### 花式索引是NumPy中的术语，它可以通过整数列表或数组进行索引

In [106]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [105]:
arr[[1,3,2]]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [ 6,  7,  8]])

In [107]:
arr[[3,2]][:,[2,1]]

array([[11, 10],
       [ 8,  7]])

### 可以使用np.ix_函数完成同样的操作

In [108]:
arr[np.ix_([3,2],[2,1])]

array([[11, 10],
       [ 8,  7]])